package dev.akre.maven.plugins.fixtures;

import org.apache.maven.model.Dependency;
import org.apache.maven.plugin.AbstractMojo;
import org.apache.maven.plugin.MojoExecutionException;
import org.apache.maven.plugins.annotations.LifecyclePhase;
import org.apache.maven.plugins.annotations.Mojo;
import org.apache.maven.plugins.annotations.Parameter;
import org.apache.maven.project.MavenProject;
import org.codehaus.plexus.archiver.ArchiverException;
import org.codehaus.plexus.archiver.jar.JarArchiver;

import javax.inject.Inject;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * Packages the compiled test fixtures into a JAR and attaches the pre-generated synthetic POM.
 */
@Mojo(
    name = "package-fixtures",
    defaultPhase = LifecyclePhase.PACKAGE,
    threadSafe = true
)
public class PackageFixturesMojo extends AbstractMojo {

    @Parameter(defaultValue = "${project}", readonly = true, required = true)
    private MavenProject project;

    @Parameter(defaultValue = "${project.build.directory}/test-fixtures-classes")
    private File fixturesOutputDirectory;

    @Parameter(defaultValue = "${project.build.directory}/${project.artifactId}-test-fixtures-${project.version}.jar")
    private File fixturesJar;

    @Parameter(defaultValue = "${project.build.directory}/${project.artifactId}-test-fixtures-${project.version}.pom")
    private File fixturesPom;

    @Parameter
    private List<Dependency> fixtureDependencies = new ArrayList<>();

    @Inject
    private JarArchiver jarArchiver;

    @Override
    public void execute() throws MojoExecutionException {
        if (!fixturesOutputDirectory.exists() || !fixturesOutputDirectory.isDirectory()) {
            getLog().info("No test fixtures found to package. Skipping.");
            return;
        }

        getLog().info("Packaging test fixtures to " + fixturesJar.getAbsolutePath());

        // 1. Create the JAR
        createJar();

        // 2. The synthetic POM is generated by compile-fixtures


        // 3. Attach artifacts to the project Context so install/deploy mojos can find them
        project.setContextValue("fixturesJar", fixturesJar.getAbsolutePath());
        project.setContextValue("fixturesPom", fixturesPom.getAbsolutePath());
    }

    private void createJar() throws MojoExecutionException {
        try {
            jarArchiver.addDirectory(fixturesOutputDirectory);
            jarArchiver.setDestFile(fixturesJar);
            jarArchiver.createArchive();
        } catch (ArchiverException | IOException e) {
            throw new MojoExecutionException("Error creating test fixtures JAR", e);
        }
    }

}
